giantswarm/cluster-vsphere

helm/cluster-vsphere/Chart.yaml

there's no point restricting this to specific kubeversions as they are only CRs.

remove kubeversion from chart metadata

---

CHANGELOG.md
helm/cluster-vsphere/templates/coredns.yaml
helm/cluster-vsphere/values.yaml

CoreDNS network policies and configuration are missing now. This PR fixes it. 
See https://github.com/giantswarm/cluster-shared/blob/main/helm/cluster-shared/templates/_coredns.tpl#L1
See https://github.com/giantswarm/cluster-cloud-director/blob/main/helm/cluster-cloud-director/templates/coredns.yaml
Verified in `gerkan`.

Fix CoreDNS configuration

---

helm/cluster-vsphere/templates/_helpers.tpl

fixing:
```
---> Deploying MC helm chart
secret/vsphere-credentials created
+ helm repo add --force-update cluster-catalog https://giantswarm.github.io/cluster-catalog/
"cluster-catalog" has been added to your repositories
+ helm upgrade --install --kubeconfig=./kubeconfigs/kind-mc-initial-gjiri.kubeconfig --version v0.2.1 --values ./secrets/values.yaml --set cluster.name=gjiri -f ./secrets/vsphere-credentials.yaml -f ./secrets/gjiri-container-registries-configuration.yaml -n org-giantswarm gjiri cluster-catalog/cluster-vsphere
Release "gjiri" does not exist. Installing it now.
Error: YAML parse error on cluster-vsphere/templates/kubeadmconfigtemplate.yaml: error converting YAML to JSON: yaml: line 57: did not find expected '-' indicator
```

Missing space (yaml indentation)

---

CHANGELOG.md
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

`organization` should be at the root level as other providers. Chart already assumes in that way. See https://github.com/giantswarm/cluster-vsphere/blob/main/helm/cluster-vsphere/templates/_helpers.tpl#L50
The location of the parameter was wrong in values.yaml and schema.
---
We use the release name for cluster name in other providers and it is easy to use.

Improve cluster parameters

---

CHANGELOG.md
helm/cluster-vsphere/templates/default-helmrepository.yaml

When debugging someone may want to set `HelmRelease` version to something like:
```
sourceRef:
kind: HelmRepository
name: pawe2-default-test
version: 0.6.1-asdfasdfasdfasdfasdf
```
with this change `pawe2-default-test` will be installed with the helm chart and does not have to be created manually. Yes it won't be used by default but I don't think that hurts.

Add default-test HelmRepository (catalog) for debugging

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

```
helm template foo helm/cluster-vsphere --set "apiServer.certSANs={'1.1.1.1','2.2.2.2'}" | grep -A6 -i sans                                                     
certSANs:
- localhost
- 127.0.0.1
- "api.foo."
- '1.1.1.1'
- '2.2.2.2'
extraArgs:
```
also the json schema for elements under `apiServer.*` were missing

Add an option to add custom certSANs

---

CHANGELOG.md
helm/cluster-vsphere/templates/cluster.yaml
helm/cluster-vsphere/values.yaml

I need it for https://github.com/giantswarm/cluster-vsphere/pull/52. I'll test it with https://github.com/giantswarm/cluster-vsphere/pull/52.
I also change the default networks to  `10.244.0.0/16` (pod) and `10.96.0.0/16` (service) as defined in https://github.com/giantswarm/giantswarm/issues/26451 because previous values were basically the same network.

Set .network.servicesCidrBlocks value in Cluster CR and change default pod and service networks

---

helm/cluster-vsphere/values.yaml

because depending on default values in lastpass might be a bit magic (`explicit > implicit`)
This also adds a logic that will use the correct container image repo based on k8s version. >=1.24 - the upstream one otherwise the vmware one

Let's provide the default value also to default values.yaml

---

CHANGELOG.md
helm/cluster-vsphere/templates/coredns-helmrelease.yaml

`1.16.0` has nodeSelector set to `node-role.kubernetes.io/control-plane=`
cc @vxav (you made the change on coredns-app so pinging you :)
current issue:
```
kube-system   coredns-controlplane-8b445ddfb-t6klq                             0/1     Pending   0             2m2s
```
```
kubectl --kubeconfig=./kubeconfigs/gjiri.kubeconfig describe pod coredns-controlplane-8b445ddfb-t6klq -n kube-system
...
Node-Selectors:              node-role.kubernetes.io/master=
Tolerations:                 node-role.kubernetes.io/control-plane:NoSchedule op=Exists
node-role.kubernetes.io/master:NoSchedule op=Exists
node.cloudprovider.kubernetes.io/uninitialized op=Exists
node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
Type …
```

Bump coredns

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml

that should help when changing the IP of control plane later on and certs need to be recreated

Add controlplane ip explicitly to certSANs list

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml

This pr: ..
<details>
```
```
</details>

Bind `kube-scheduler` metrics to 0.0.0.0

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml

Towards https://github.com/giantswarm/klingel/issues/91
This pr:
- Set value for terminated pod gc threshold to be consistent with vintage
<details>
```
```
</details>

Set value for terminated pod gc threshold to be consistent with vintage

---

CHANGELOG.md
helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml

Bumps cloud-provider-vsphere to latest
<details>
```
```
</details>

Bump cloud-provider-vsphere version

---

helm/cluster-vsphere/templates/ipam/ipAddressClaim.yaml

I didn't realise that `InClusterIPPool` were namespace scoped. The global CR should work, otherwise the `InClusterIPPool` would need to be installed for each organisation and with different ip range. However if that's something that a customer needs, it's easy to switch back or even make this configurable.

InClusterIPPool -> GlobalInClusterIPPool (namespace scope not required)

---

CHANGELOG.md
helm/cluster-vsphere/templates/cilium-helmrelease.yaml
helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/templates/coredns-helmrelease.yaml

This pr: adds a way to change the timeouts for helm releases. Since it's not part of public API, there are no defaults in the `values.yaml` file

Customizable timeouts

---

CHANGELOG.md
helm/cluster-vsphere/files/etc/containerd/config.toml
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/templates/containerd-config-secret.yaml
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/templates/registry-secret.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This PR:
- Consolidate the full `config.toml` configuration file for containerd into a single file to address [#1737](https://github.com/giantswarm/roadmap/issues/1737)
@erkanerol as discussed in https://gigantic.slack.com/archives/C01BYMF6RN0/p1689847741604689?thread_ts=1689844311.988129&cid=C01BYMF6RN0 can you verify it when using the `credentials and mirrors` configurations ? the structure of values has not changed for those settings
<details>
```
```
</details>

Consolidate containerd config.toml into single file

---

CHANGELOG.md
helm/cluster-vsphere/templates/_helpers.tpl

towards https://github.com/giantswarm/giantswarm/issues/27037
This PR:
- adds user  nobody  to group  root  to allow node-exporter to access the host's filesystem.
this aligns with CAPA.

add user nobody to root group

---

CHANGELOG.md
helm/cluster-vsphere/templates/cilium-helmrelease.yaml

Towards https://github.com/giantswarm/giantswarm/issues/27728
Conformance tests have failed with this error
```
[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]
```
As far as I understand from [this](https://github.com/giantswarm/roadmap/issues/1346) issue, it is because of the cilium version. CAPZ passed the conformance tests and it has the newer version. This change is supposed to fix the conformance tests.
I applied the toleration changes in CAPVCD to this manifest too. See https://github.com/giantswarm/cluster-cloud-director/commit/bf00c740f80e2b910a182cd1ea0dfe0c0353cc35
<details>
```
```
</details>

Bump cilium app version to 0.10.0

---

CHANGELOG.md
helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/templates/ipam/_ipam.tpl
helm/cluster-vsphere/templates/ipam/assign-ip-pre-install-job.yaml
helm/cluster-vsphere/templates/ipam/ipAddressClaim.yaml
helm/cluster-vsphere/templates/ipam/ipAddressClaimLB.yaml
helm/cluster-vsphere/templates/ipam/rbac.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

issue: https://github.com/giantswarm/giantswarm/issues/28655
This pr:
- adds a way to auto-assign an IP for service LB running in WC (kube-vip).
Kube-vip cloud provider watches for services of type LB and assigns a new ip for them from a range. This range is configured in WC using a configmap called `kubevip@kube-system`. 
However, we need to populate the content of the configmap upfront during the cluster creation (we currently ship kube-vip and kubevip-cloud-provider as sub-chart in our "CPI bundle") and more importantly we need to somewhere keep track of what IPs have been used. Each WC requires at least 1 IP to work properly, because the ingress of nginx controller needs to be exposed using this mechanism. Then other stuff, like grafana, dex, anthena, prometheus, happa can be exposed …

IPAM for service LB in WC

---

helm/cluster-vsphere/templates/ipam/assign-ip-pre-install-job.yaml

because of the 'set -o errexit'
```
λ kubectl logs -f flatcar12-update-values-hook-kx8zw -n org-giantswarm -c get-ip-for-control-plane                                                                                                                        17s ○ gcapeverde-admin@gcapeverde
waiting for a free IP address..
Error from server (NotFound): ipaddresses.ipam.cluster.x-k8s.io "flatcar12" not found
```
instead of looping and waiting. This happens when there are no more free ip in the pool.

When IP was not obtained it failed after first attempt 

---

CHANGELOG.md
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/templates/cilium-helmrelease.yaml
helm/cluster-vsphere/templates/coredns-helmrelease.yaml
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml

Allign cilium&coredns version with cluster-aws to check if it fixes cert-manager installation issues.
<details>
```
```
</details>

Bump cilium and coredns versions

---

CHANGELOG.md
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This pr: ..
<details>
```
```
</details>

Remove TTLAfterFinished for 1.25 compatibility

---

CHANGELOG.md
helm/cluster-vsphere/files/kubelet-args
helm/cluster-vsphere/values.yaml

Enabled by default since 1.11 => https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/
<details>
```
```
</details>

remove ExpandPersistentVolumes

---

helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/templates/kubevip-staticpod-template.yaml

the host alias record for the static kubevip pod had to be added to workaround https://github.com/kube-vip/kube-vip/issues/287
otherwise the pod was not starting:
```
E1124 11:23:45.545715       1 leaderelection.go:327] error retrieving resource lock kube-system/plndr-cp-lock: Get "https://kubernetes:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/plndr-cp-lock": dial tcp: lookup kubernetes on 10.10.223.5:53: no such host
```
Another required change is the prometheus port. The old version didn't ship the prom exporter so it worked, but new ones do and the default is `2112`. We deploy 2 flavors of kubevips:
1) for CPs (having the `cp_enable=true && svc_enable=false`) 
1) for all the nodes (having `svc_enable=true && cp_enable=false`)
This means that on CP there will be two …

Bump kubevip to new version + consuming our own retagged images

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/values.schema.json

We are receiving this error in the CI
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.apiServer.extraArgs.feature-gates, unknown object type "nil" in KubeadmControlPlane.spec.kubeadmConfigSpec.clusterConfiguration.controllerManager.extraArgs.feature-gates]
```
This PR fixes the issue. 
<details>
```
```
</details>

Fix templating issues for featureGates

---

CHANGELOG.md
helm/cluster-vsphere/files/etc/teleport.yaml

Towards https://github.com/giantswarm/giantswarm/issues/30398
- Add new `ins=` label to all nodes, same value as mc= label
- Removes conditional check for `cluster=` label for MC nodes
Currently, our labels doesn't support listing only MC nodes, because cluster= label is not present on MC nodes, only WC nodes and mc= label is common on all nodes.
In Web UI, we can filter by setting cluster="" but same doesn't work on Terminal tsh client.
```
$ tsh ssh root@mc=gazelle,cluster=
ERROR: invalid label spec: 'mc=gazelle,cluster=', should be 'key=value'
$ tsh ssh root@mc=gazelle,cluster=""
ERROR: invalid label spec: 'mc=gazelle,cluster=', should be 'key=value'
```

Update teleport node labels cluster

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cilium-helmrelease.yaml
helm/cluster-vsphere/templates/helmreleases/netpol-helmrelease.yaml

This PR disables the extra network policies on the cilium app and enable it on the network-policies-app
Towards https://github.com/giantswarm/roadmap/issues/3261

Move extra network policies

---

helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This pr removes our ability to set etcd images (and coredns which wasn't used like that anyways). This means it will be handled automatically by kubeadm.
This also aligns with our cloud providers.
https://gigantic.slack.com/archives/CLPMFRVU6/p1712831360621509?thread_ts=1712831054.292869&cid=CLPMFRVU6

Remove etcd and dns images from kubeadmcontrolplane

---

CHANGELOG.md
helm/cluster-vsphere/ci/ci-values.yaml
helm/cluster-vsphere/files/etc/containerd/config.toml
helm/cluster-vsphere/files/etc/teleport.yaml
helm/cluster-vsphere/templates/_cluster_dns.tpl
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/templates/_ssh.tpl
helm/cluster-vsphere/templates/cluster.yaml
helm/cluster-vsphere/templates/helmreleases/cilium-helmrelease.yaml
helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/templates/helmreleases/coredns-helmrelease.yaml
helm/cluster-vsphere/templates/ipam/_ipam.tpl
helm/cluster-vsphere/templates/ipam/assign-ip-pre-install-job.yaml
helm/cluster-vsphere/templates/ipam/ipAddressClaim.yaml
helm/cluster-vsphere/templates/ipam/ipAddressClaimLB.yaml
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/templates/kubevip-staticpod-template.yaml
helm/cluster-vsphere/templates/vspherecluster.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Notes: 
- it's not possible to test this using the e2e CI tests because the [test cluster values](https://github.com/giantswarm/cluster-standup-teardown/blob/main/pkg/clusterbuilder/providers/capv/values/cluster_values.yaml) have not been updated yet (and cannot be updated until the chart refactoring is complete and released). Running the CI tests locally with manually updated values passes though:
```
Ran 18 of 27 Specs in 1850.070 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
Ginkgo ran 1 suite in 30m59.16497128s
Test Suite Passed
```

refactor: aggregate connectivity values under global key

---

CHANGELOG.md
helm/cluster-vsphere/ci/ci-values.yaml
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
helm/cluster-vsphere/templates/vspheremachinetemplate.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Notes: 
- it's not possible to test this using the e2e CI tests because the [test cluster values](https://github.com/giantswarm/cluster-standup-teardown/blob/main/pkg/clusterbuilder/providers/capv/values/cluster_values.yaml) have not been updated yet (and cannot be updated until the chart refactoring is complete and released). Running the CI tests locally with manually updated values passes though:
```
Ran 18 of 27 Specs in 2127.030 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
Ginkgo ran 1 suite in 35m34.747568803s
Test Suite Passed
```

refactor: move controlplane values under global key

---

CHANGELOG.md
helm/cluster-vsphere/ci/ci-values.yaml
helm/cluster-vsphere/templates/kubeadmconfigtemplate.yaml
helm/cluster-vsphere/templates/machinedeployment.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Notes: 
- it's not possible to test this using the e2e CI tests because the [test cluster values](https://github.com/giantswarm/cluster-standup-teardown/blob/main/pkg/clusterbuilder/providers/capv/values/cluster_values.yaml) have not been updated yet (and cannot be updated until the chart refactoring is complete and released). Running the CI tests locally with manually updated values passes though:
```
Ran 18 of 27 Specs in 1839.581 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
Ginkgo ran 1 suite in 30m48.547890827s
Test Suite Passed
```

refactor: move nodepools under global key

---

CHANGELOG.md
helm/cluster-vsphere/ci/ci-values.yaml
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/templates/provider-secret.yaml
helm/cluster-vsphere/templates/vspherecluster.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Notes: 
- it's not possible to test this using the e2e CI tests because the [test cluster values](https://github.com/giantswarm/cluster-standup-teardown/blob/main/pkg/clusterbuilder/providers/capv/values/cluster_values.yaml) have not been updated yet (and cannot be updated until the chart refactoring is complete and released). Running the CI tests locally with manually updated values passes though:
```
Ran 18 of 27 Specs in 2174.162 seconds
SUCCESS! -- 18 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
Ginkgo ran 1 suite in 36m22.416968005s
Test Suite Passed
```

refactor: create providerSpecific key under global

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/templates/_helpers.tpl
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This PR sets default k8s version `1.26.15`.

Bump k8s version to 1.26.15

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml

This pr removes the kube-vip values set in the cloud provider's HelmRelease.
Towards `1.` in https://github.com/giantswarm/roadmap/issues/3467

remove kube-vip values

---

CHANGELOG.md
examples/cluster-manifest.yaml
helm/cluster-vsphere/README.md
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This PR updates the default k8s version as 1.27.14

Bump k8s version to 1.27.14

---

CHANGELOG.md
helm/cluster-vsphere/templates/ipam/assign-ip-pre-install-job.yaml

The pre-install hook for IPAM fails with this error
```
❯ k logs t-2lyjs48jftdkqcis2p-update-values-hook-tpkzm -c get-ip-for-control-plane
waiting for a free IP address..
Error from server (Forbidden): ipaddresses.networking.k8s.io "t-2lyjs48jftdkqcis2p" is forbidden: User "system:serviceaccount:org-t-f6e19e51e741rxmeon:t-2lyjs48jftdkqcis2p-update-values-hook" cannot get resource "ipaddresses" in API group "networking.k8s.io" at the cluster scope
```
because k8s 1.27 introduced a new API group for networking: `networking.k8s.io/v1alpha1`
This PR adds the API group (`ipam.cluster.x-k8s.io`) of `cluster-api-ipam-provider-in-cluster` for `ipaddresses` CRs explicitly in the pre-install hook.

Fix IPAM's pre-install hook for k8s 1.27

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
helm/cluster-vsphere/files/etc/containerd/config.toml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Towards: https://github.com/giantswarm/roadmap/issues/3460
Related to: https://github.com/giantswarm/cluster/pull/178

Support local registry caches

---

CHANGELOG.md
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

Simon did a stupid when refactoring the chart. Luckily Helm seems to ignore the issue and cluster charts in use were unaffected.
The defaults can be removed as the definition of `network` already contains the correct defaults.

Correct default values for networks in values schema

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cleanup-helmreleases-hook-job.yaml

This pr: fixes a bug where a cluster is still paused on deletion and therefore not cleaned up properly.
https://github.com/giantswarm/giantswarm/issues/31319

unpause cluster in cleanup hook

---

CHANGELOG.md
helm/cluster-vsphere/templates/ipam/_ipam.tpl
helm/cluster-vsphere/templates/ipam/ipAddressClaim.yaml
helm/cluster-vsphere/templates/ipam/ipAddressClaimLB.yaml

This pr:
Updates the API version for IPAM components as installation was failing when using v1alpha1. Required for [mc-bootstrap](https://github.com/giantswarm/mc-bootstrap/pull/934)

Update ipam API versions to v1beta1

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cleanup-helmreleases-hook-job.yaml
helm/cluster-vsphere/templates/ipam/assign-ip-pre-install-job.yaml

related https://github.com/giantswarm/roadmap/issues/3619
This pr: fixes the hooks failing due to ambiguous api groups on some MCs (specifically this is the case on goat)

set cluster api group in hooks

---

CHANGELOG.md
helm/cluster-vsphere/templates/ipam/_ipam.tpl

We have default for `.global.connectivity.network.loadBalancers.ipPoolName` and it is not easy to set it empty to disable IPAM. On the other hand, we set `.global.connectivity.network.loadBalancers.cidrBlocks` when we don't want to use IPAM. Thanks to this additional check, we don't have to overwrite the `.global.connectivity.network.loadBalancers.ipPoolNam` with null.

Fix IPAM for service load balancers

---

CHANGELOG.md
helm/cluster-vsphere/values.schema.json

Our customer requires to place the VMs in a specific folder which is not exposed in the interface. Rather than supporting every configuration field in CAPV (there are a lot), we can open it.

enable add properties

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cilium-helmrelease.yaml

Upstream marked 'strict' as deprecated in 1.15 and will remove it completely in 1.16.
See also cilium/cilium#32711
Signed-off-by: Matias Charriere <matias@giantswarm.io>
Towards https://github.com/giantswarm/giantswarm/issues/31353

 Set cilium kubeProxyReplacement to 'true'

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This pr adds the capability to specify a storage policy or none for the default vSphere csi storage class. Setting no storage policy is required in some cases.
It is also possible to not create a default policy and set the reclaimPolicy. Here we only create one SC as we never really used the reclaim policy.
The idea is to offer the customer the ability to easily create a default SC, other SCs can be created manually.
Consumes https://github.com/giantswarm/cloud-provider-vsphere-app/pull/136
Towards https://github.com/giantswarm/roadmap/issues/3626

configurable storage class

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/values.schema.json

I missed this when completing the work for 0.60.0

Rename caFile to caPem in values schema

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/values.schema.json

This pr:
allows the management cluster name in the values schema at the new location (i.e. not in the root context). this is required for the shared cluster chart (specifically the teleport configuration).

Allow .Values.global.managementCluster in values schema

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubevip-staticpod-template.yaml

This PR:
- adds the renovate tag to ensure the kube-vip static pod manifest is updated automatically.

Use Renovate to update kube-vip static pod manifest

---

CHANGELOG.md
helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml

This pr:
Allows the CPI helmrelease to pick up the catalog from the Release CRD.

Make cloud-provider-vsphere HelmRelease catalog configurable

---

CHANGELOG.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/ci/test-multiple-mirrors-with-auth-and-local-caching.yaml
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

https://github.com/giantswarm/giantswarm/issues/32341
This pr: ..

add components.containerd

---

CHANGELOG.md
README.md
helm/cluster-vsphere/README.md
helm/cluster-vsphere/ci/ci-values.yaml
helm/cluster-vsphere/templates/helpers/_controlplane.tpl
helm/cluster-vsphere/templates/helpers/_workers.tpl
helm/cluster-vsphere/values.schema.json
helm/cluster-vsphere/values.yaml

This pr adds a field to add a suffix to the vSphere VM template name to clone the node VMs from.
Towards https://github.com/giantswarm/giantswarm/issues/32591
Setting `global.providerSpecific.templateSuffix=paris` will generate:
```yaml
template: flatcar-stable-N/A-kube-N/A-tooling-N/A-gs-paris
```
Not setting `global.providerSpecific.templateSuffix` will generate:
```yaml
template: flatcar-stable-N/A-kube-N/A-tooling-N/A-gs
```

add-template-suffix-field

---

CHANGELOG.md
helm/cluster-vsphere/templates/kubevip-staticpod-template.yaml

the latest kube-vip release has a [breaking change](https://github.com/kube-vip/kube-vip/releases/tag/v0.9.0) which needs to be fixed at the same time as the image upgrade.
closes https://github.com/giantswarm/cluster-vsphere/pull/356

update kube-vip staticpod template to 0.9.0
