giantswarm/cluster-vsphere

CHANGELOG.md, helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml, helm/cluster-vsphere/values.schema.json, helm/cluster-vsphere/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/22454
=> Set etcd image to retagged 3.5.4 by default

helm/cluster-vsphere/values.schema.json
Towards https://github.com/giantswarm/roadmap/issues/2098
This PR applies `schemalint normalize` to the schema. The effect is that key order and white space get normailzed and subsequent PRs will not contain such purely cosmetic changes.
=> Normalize values schema

CHANGELOG.md, helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml
Perhaps this should be configurable using the values? With something like
```
cloudProviderVsphereVersion: 1.3.3
```
=> Bump cloud-provider-vsphere version to 1.3.3

CHANGELOG.md, helm/cluster-vsphere/templates/machinehealthcheck.yaml
Towards https://github.com/giantswarm/roadmap/issues/2022
=> Add machine health check for worker nodes

CHANGELOG.md, helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml, helm/cluster-vsphere/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/26409
=> Consume cloud-provider-vsphere version including kube-vip

CHANGELOG.md, helm/cluster-vsphere/templates/_helpers.tpl, helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
towards https://github.com/giantswarm/giantswarm/issues/25275
=> fix permissions on kubelet dir for node-exporter

CHANGELOG.md, helm/cluster-vsphere/ci/ci-values.yaml, helm/cluster-vsphere/values.yaml
issue: https://github.com/giantswarm/roadmap/issues/2338
=> k8s version bump

CHANGELOG.md, helm/cluster-vsphere/files/etc/kubernetes/policies/audit-policy.yaml, helm/cluster-vsphere/templates/_helpers.tpl, helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
Towards https://github.com/giantswarm/roadmap/issues/2194
Copied audit log policy files from other providers: https://github.com/giantswarm/cluster-gcp/blob/a3a3984c032c9c8a457ac334bccd6a0cc70a3d54/helm/cluster-gcp/files/etc/kubernetes/policies/audit-policy.yaml
=> Add auditlog configuration

CHANGELOG.md, helm/cluster-vsphere/ci/ci-values.yaml, helm/cluster-vsphere/templates/_cluster_dns.tpl, helm/cluster-vsphere/templates/cloud-provider-vsphere-helmrelease.yaml, helm/cluster-vsphere/templates/cluster.yaml, helm/cluster-vsphere/templates/coredns-helmrelease.yaml, helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml, helm/cluster-vsphere/templates/vspherecluster.yaml, helm/cluster-vsphere/values.schema.json, helm/cluster-vsphere/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/26802
=> Unify network api

CHANGELOG.md, helm/cluster-vsphere/templates/cilium-helmrelease.yaml, helm/cluster-vsphere/values.schema.json, helm/cluster-vsphere/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/23014
Towards https://github.com/giantswarm/roadmap/issues/1949
=> Stop deploying default network policies with the cilium-app

.github/pull_request_template.md
waiting for:
- https://github.com/giantswarm/cluster-test-suites/pull/24
=> Add template for pr

examples/README.md, examples/cluster-manifest.yaml
This pr: ..
<details>
```
```
</details>
=> add example

examples/cluster-manifest.yaml
This pr: updates the example values, yaml
<details>
```
```
</details>
=> svc lb ipam 4 example values.yaml

CHANGELOG.md, helm/cluster-vsphere/templates/kubeadmcontrolplane.yaml
https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#klog
<details>
```
```
</details>
=> drop logtostderr

CHANGELOG.md, helm/cluster-vsphere/templates/helmreleases/cleanup-helmreleases-hook-job.yaml
This pr: ..
<details>
```
```
</details>
=> Fix cleanup of netpol helmrelease

CHANGELOG.md, helm/cluster-vsphere/Chart.yaml
=> Add icon for the chart

.github/pull_request_template.md, renovate.json5
This PR:
Automatically triggers E2e tests on new PRs which includes renovate PRs.
Issue: https://github.com/giantswarm/giantswarm/issues/29379
=> Trigger e2e tests automatically on PR creation.

Makefile, helm/cluster-vsphere/README.md
Towards https://github.com/giantswarm/giantswarm/issues/29628
=> Generate schema docs in the project

CHANGELOG.md, helm/cluster-vsphere/templates/helmreleases/netpol-helmrelease.yaml
=> disable default coredns ccnp

CHANGELOG.md, helm/cluster-vsphere/values.yaml
towards https://github.com/giantswarm/roadmap/issues/3245
=> Switch container registry to gsoci.azurecr.io

CHANGELOG.md, helm/cluster-vsphere/values.schema.json, helm/cluster-vsphere/values.yaml
This pr cleans up the values files, fixes some parts of the schema and sets additional defaults
=> Improve values defaults and schema

CHANGELOG.md, helm/cluster-vsphere/values.schema.json
This pr:
normalises the json schema using `schemalint`
The diff is massive, but that's because all the indentation has been changed.
=> normalise JSON schema

CHANGELOG.md, examples/cluster-manifest.yaml
- **migrate example values to new format**
- **update example manifest and remove defaulted values**
- **update app versions**
- **update changelog**
=> refactor: update example manifests

CHANGELOG.md, helm/cluster-vsphere/values.schema.json
This PR introduces no changes to the values structure, it only moves as much into the definitions as possible.
Each individual commit is standalone so it will be easier to review them individually rather than all at once.
=> refactor: optimise chart by using more definitions in values schema"

CHANGELOG.md, helm/cluster-vsphere/templates/helmreleases/cleanup-helmreleases-hook-job.yaml
towards https://github.com/giantswarm/giantswarm/issues/31433
=> Fix syntax error with helmrelease cleanup hook

CHANGELOG.md
=> add missing migration steps to changelog

CHANGELOG.md
https://gigantic.slack.com/archives/C01BYMF6RN0/p1725523551347349
=> Update 0.61.0 upgrade procedure

CHANGELOG.md
=> add changlog entry for kube-vip fix

CHANGELOG.md
=> update changelog with cluster chart bump

CHANGELOG.md, helm/cluster-vsphere/README.md, helm/cluster-vsphere/values.schema.json, helm/cluster-vsphere/values.yaml
=> Update kubectl image used by IPAM job to 1.29.9

CHANGELOG.md, examples/cluster-manifest.yaml
This pr: ..
- updates the example manifest.
=> update example manifest

examples/cluster-manifest.yaml
This pr:
fixes the example manifest.
=> remove empty array from example manifest

CHANGELOG.md
This pr:
Is just some housekeeping.
=> update changelog before releasing

CHANGELOG.md, helm/cluster-vsphere/values.schema.json
towards https://github.com/giantswarm/giantswarm/issues/32498
=> Remove requirement for 'pods' and 'services' as they are defaulted by the values schema

helm/cluster-vsphere/templates/helmreleases/cloud-provider-vsphere-helmrelease.yaml, helm/cluster-vsphere/templates/helmreleases/kube-vip-cloud-provider-helmrelease.yaml, helm/cluster-vsphere/templates/ipam/rbac.yaml
This pr: ..
Fixes some minor issues discovered with the chart
=> Minor chart fixes
